name: Build containers

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: self-hosted
    env:
      IMAGE_TAG: ${{ github.sha }}
    defaults:
      run:
        working-directory: Infrastructure
    steps:
      - uses: actions/checkout@v7
      - run: |
          cp "$HOME/edu_lab/CICD_Lab/Infrastructure/.env" .env
          docker compose build nginx
          docker compose up -d nginx
          echo "nginx build complete" 
          docker compose build grafana
          docker compose up -d grafana
          echo "grafana build complete"