name: Docker cleaner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1'  #every week on sunday at 1:00 AM

jobs:
    cleaner:
      runs-on: self-hosted
      steps:
        - name: old images cleaner
          run: |
            docker image prune -af
            echo "images cleaned"

        - name: build cache cleaner    
          run: |
            docker builder prune -f
            echo "build cache cleaned"

        - name: network cleaner
          run: |
            docker network prune -f
            echo "networks cleaned"
        
      #check after with 'docker system df -h'