name: test1

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: echo "Hello, World!"
  docker-build:
    runs-on: self-hosted
    env:
      working-directory: ./CICD_Lab/Infrastructure
    steps:
      - uses: actions/checkout@v3
      - run: docker compose build nginx
      - run: echo "nginx build complete"