name: test1

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: echo "Hello, World!"
  docker-build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: Infrastructure
    steps:
      - uses: actions/checkout@v7
      - run: docker compose build nginx
      - run:docker compose up -d nginx
      - run: echo "nginx build complete"