name: test1

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - run: echo "Hello, World!"
  docker-build:
    runs-on: self-hosted
    steps:
      - name: nginx-build
        - run: docker compose build nginx
        - run: echo "nginx build complete"